# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "test" ]
    # This ensures the pipeline ONLY runs if these files change
    paths:
      - 'models/**'
      - 'data/question_embeddings.csv'
      - 'status.txt'
      - 'test_queries.json'
  pull_request:
    branches: [ "main", "test" ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      #- name: Install system tflite runtime
      #  run: |
      #    sudo apt update
      #    sudo apt install -y python3-tflite-runtime
      - name: Start build
        run:  echo "Starting build.."
        
      # Runs a single command using the runners shell
      #- name: Create virtual environment
      #  run: |
      #    echo "Building the new commit!"
      #    python3 -m venv venv --system-site-packages
      #    source venv/bin/activate
      #    python3 --version
      #    pip install --upgrade pip 
      #    pip install -r requirements.txt
        
  test:
    runs-on: self-hosted
    needs: build

    steps: 
      - uses: actions/checkout@v4

      - name: Start test phase
        run: echo "Starting test job..."

      - name: Run embedding comparison script
        run: |
          echo "Running embedding comparison logic..."
          python3 -m venv venv --system-site-packages
          source venv/bin/activate
          python3 --version
          pip install --upgrade pip 
          pip install -r requirements.txt
          python3 main.py
          echo "Test job completed."
          touch cicd.test

  deploy: 
    runs-on: self-hosted
    needs: test

    steps:
      - name: Deploy stage
        run: |
          echo "All checks passed."
          echo "Code is ready to deploy." >> ~/Deployment_status.txt
      
    
  
